import React from "react";
import dog1 from './videos/dog1.mp4';
import dog2 from './videos/dog2.mp4';
import dog3 from './videos/dog3.mp4';
import dog4 from './img/image1.png';
import dog5 from './videos/dog5.mp4';
import dog6 from './videos/dog6.mp4';
import dog7 from './videos/dog7.mp4';
import dog8 from './videos/dog8.mp4';
import dog9 from './videos/dog9.mp4';
import dog10 from './videos/dog10.mp4';
import dog11 from './videos/dog11.mp4';
import dog12 from './videos/dog12.mp4';
import dog13 from './videos/dog13.mp4';
import dog14 from './videos/dog14.mp4';
import dog15 from './videos/dog15.mp4';
import dog17 from './videos/dog17.mp4';
import dog18 from './videos/dog18.mp4';
import dog19 from './videos/dog19.mp4';
import dog20 from './img/image2.jpg';
import dog21 from './videos/dog21.mp4';
import dog22 from './videos/dog22.mp4';
import dog23 from './videos/dog23.mp4';
const dog16 = "Fyn580ZD91U"
const dog24 = "0zYW6NXnDOU"

export default [
  {type: 'mp4', src: dog1},
  {type: 'mp4', src: dog2},
  {type: 'mp4', src: dog3},
  {type: 'image', src: dog4},
  {type: 'mp4', src: dog5},
  {type: 'mp4', src: dog6},
  {type: 'mp4', src: dog7},
  {type: 'mp4', src: dog8},
  {type: 'mp4', src: dog9},
  {type: 'image', src: dog20},
  {type: 'mp4', src: dog10},
  {type: 'mp4', src: dog11},
  {type: 'mp4', src: dog12},
  {type: 'mp4', src: dog13},
  {type: 'mp4', src: dog14},
  {type: 'mp4', src: dog15},
  {type: 'youtube', src: dog16},
  {type: 'mp4', src: dog17},
  {type: 'mp4', src: dog18},
  {type: 'mp4', src: dog19},
  {type: 'mp4', src: dog21},
  {type: 'mp4', src: dog22},
  {type: 'mp4', src: dog23},
  {type: 'youtube', src: dog24},
]
